---
- name: The .pgpass file
  copy:
    dest: '/var/lib/pgsql/.pgpass'
    content: "{{ hostvars[groups['primary'][0]]['ansible_ssh_host'] }}:5432:{{ replication_db }}:{{ replication_user }}:{{ replication_user_password }}"
    owner: postgres
    group: postgres
    mode: 0600
  tags:
    - test-streaming

- name: Ensure that '{{ postgresql_service }}' is stopped
  service:
    name: '{{ postgresql_service }}'
    state: stopped
  tags:
    - test-streaming

- name: Ensure that the database directory is empty '{{ dbpath }}'
  file:
    path: "{{ dbpath }}"
    state: absent
  become: yes
  become_method: sudo
  become_user: postgres
  tags:
    - test-streaming

- name: Seed the backup database server with initial information from the primary server "{{ hostvars[groups['primary'][0]]['ansible_ssh_host'] }}"
  command: pg_basebackup -h "{{ hostvars[groups['primary'][0]]['ansible_ssh_host'] }}" -D "{{ dbpath }}" -P -U "{{ replication_user }}" --xlog-method=stream
  args:
    creates: '{{ dbpath }}/PG_VERSION'
  become: yes
  become_method: sudo
  become_user: postgres
  tags:
    - test-streaming

- name: Template configuration file installation for backup database '{{ ansible_hostname }}'
  template:
    src: '{{ item }}.conf.j2'
    dest: '{{ dbpath }}/{{ item }}.conf'
    owner: postgres
    group: postgres
  with_items:
    '{{ config_files }}'
  become: yes
  become_method: sudo
  become_user: postgres
  tags:
    - test-streaming

- name: Start the backup database server '{{ ansible_hostname }}'
  become: yes
  become_user: root
  become_method: sudo
  service:
    name: '{{ postgresql_service }}'
    state: started
    enabled: yes
  tags:
    - test-streaming
